# Generated by Django 4.0.3 on 2022-12-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodvenue', '0005_answer_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
