# Generated by Django 4.0.3 on 2023-01-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
    ]
