# Generated by Django 4.0.3 on 2023-01-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
